### ISSUE TITLE
Custom UI Text bugged

### ISSUE THREAD

**Issue by levikoe** [AdvancedPlugins/Seasons#1]
### Describe the bug

Calander from the provided custom UI is bugged 

Using it via Itemsadder

![image](https://github.com/AdvancedPlugins/Seasons/assets/112263031/0261cfbe-6ffa-453d-be2b-27f1966b86bf)

### How to reproduce

i just installed the ui following the steps in the text document

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Seasons/assets/112263031/414f3aff-83ee-4c1e-8ef5-1cc333d064af)

**Comment by GC-spigot** [comment]
Will be fixed in ~15 minutes :)
