### ISSUE TITLE
Add more placeholders for customization

### ISSUE THREAD

**Issue by Ricozaur** [AdvancedPlugins/Seasons#100]
### Describe the feature

Like %advancedseasons_temperature_icons%, with the thermometer icons with it and the colors, just like in the actionbar, instead of just the number. To put in a scoreboard for example. 

%advancedseasons_event%, for when an event is going on like Halloween.

%advancedseasons_tempevents% to display action bar temp events somewhere else.

**Comment by Halogly** [comment]
yes, i need it too. because i need to use BetterHud to change the actionbar's position, like the top and right of the screen. but now the plugin doesn't have icon, event etc. placeholder yet, it's a bit of a pity
