### ISSUE TITLE
lands compatibility does not work properly

### ISSUE THREAD

**Issue by homerek111** [AdvancedPlugins/Seasons#103]
### Describe the bug

snow + ice is creating in my land's region in winter (it shouldnt)
I also have worlguard and on worldguard region it does not happen 

so there must be something wrong with lands compatibility... 

### How to reproduce

i use the latest lands 7.2.3
and 1.2.8 advancedseasons

advancedseasons config option that should prevent it from happening:

# Should land protection plugins be ignored?
# If true, AdvancedSeasons will ignore land protection plugins and will be able to change blocks in protected areas
# This may have impact on performance depending on land protection plugins
ignoreLandProtection: false

### Screenshots / Videos

![obraz](https://github.com/AdvancedPlugins/Seasons/assets/93496464/4855aac0-7c6a-4349-8ab9-60720fc8ff92)

**Comment by homerek111** [comment]
@GC-spigot could you please update lands compatibility - i would be really greatful

**Comment by Ynverxe** [comment]
Fixed!

**Comment by homerek111** [comment]
> Fixed!

@Ynverxe Nice! :) Before you release the update consider checking this callendar gui's title bug as well: https://github.com/AdvancedPlugins/Seasons/issues/104

**Comment by homerek111** [comment]
> Fixed!

when +/- can we expect the new release with the fix? :)

**Comment by homerek111** [comment]
> Fixed!

@Ynverxe when +/- can we expect the new release with the fix? :)

**Comment by SirJben** [comment]
@Ynverxe still occurs in latest version.

**Comment by homerek111** [comment]
@Ynverxe please fix it...

**Comment by Ynverxe** [comment]
Hi, fixed it again. Sorry for the delay.

**Comment by homerek111** [comment]
> Hi, fixed it again. Sorry for the delay.

nice :) I hope you will release it on spigot this time...
