### ISSUE TITLE
Mythic Mobs not spawning in.

### ISSUE THREAD

**Issue by Ricozaur** [AdvancedPlugins/Seasons#105]
### Describe the bug

The MythicMobs don't get recognized without :hostile
and for the other i have to put something after it like :docile
to make it recognizable.

### How to reproduce

This is what my config looks like:
https://mclo.gs/FCMtasO

The MythicMobs names are identical.

### Screenshots / Videos

https://mclo.gs/FCMtasO

### Server Log

none

**Comment by Ynverxe** [comment]
Fixed. However, if you want a "docile" mob, don't use the ":docile" sufix. AS interprets it as non-hostile by default.

**Comment by Ricozaur** [comment]
Thankss, gonna experiment with it again
