### ISSUE TITLE
Biome temperature not working for custom biomes

### ISSUE THREAD

**Issue by Mitality** [AdvancedPlugins/Seasons#107]
### Describe the bug

Custom biomes appear to still use the default temperature, despite being added to the biome configuration.

For example, `DESERT` and `ancient_sands` don not share temperature if configured like so:

**badlands_deserts.yml:**
```
biomes:
  - DESERT
  - ancient_sands

temperature: 15
```

**config.yml:**
```
defaultColorBiomes:
  - DESERT
  - ancient_sands
```

With this config, `DESERT` is 15°C warmer than `ancient_sands`.

`DESERT` uses the default temperature **plus 15°C** and `ancient_sands` just uses the default temperature without applying the biome specific temperature from badlands_deserts.yml.

### How to reproduce

- Use a datapack, plugin or mod that adds custom biomes to your server.
- Add a custom biome to your biome configuration and set a biome specific temperature that should be added to the default temperature. (e.g. 15 like in the example above = default temperature + 15)
- Add your custom biome to defaultColorBiomes in config.yml to ensure it keeps its enviroment (Don't know if that matters)
- Visit the biome in game and compare it to a vanilla biome in the same biome configuration file that should theoretically use the same temperature to notice the difference.

**Comment by Ynverxe** [comment]
Working on it :+1:

**Comment by Ynverxe** [comment]
Improved custom biome support in 1.3.9.
