### ISSUE TITLE
Unhandled exception with Multiverse Core

### ISSUE THREAD

**Issue by ShadySt** [AdvancedPlugins/Seasons#108]
### Describe the bug

I'm using Multiverse Core 4.3.12, Advanced Seasons 1.3.2, server is Paper 1.20.4
If you enable seasons in any non default world and then restart server - plugin throws errors and stops working on player login.  

### How to reproduce

- Have Multiverse Installed 
- Have Advanced Seasons installed
- Import new world and enable seasons in it
- (Everything works fine, unless...)
- Server restarts
- Now, anytime somebody connects to server, Advanced Seasons throws many errors in console and stops working completely.
--------------------------------------------
- If you have Multiverse installed and you enable seasons only in your default world, mentioned in server.properties - everything seems to work fine. 

### Screenshots / Videos

https://prnt.sc/ckGuOHxyvsQg
https://prnt.sc/j9oHNlk0LTX_

### Server Log

https://mcpaste.io/f30715f16451e339

**Comment by GC-spigot** [comment]
Should be working now
