### ISSUE TITLE
 java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3

### ISSUE THREAD

**Issue by AsunaTsuki** [AdvancedPlugins/Seasons#109]
### Describe the bug

When installing 1.2.3 or 1.2.4 on PaperMC 1.20.6 i get the java error in the log attached.

### How to reproduce

install the plugin and try starting the server

### Server Log

https://mcpaste.io/165dbdfd7b4da42d

**Comment by GC-spigot** [comment]
Solved
