### ISSUE TITLE
Unbreakable snow

### ISSUE THREAD

**Issue by Pilvinen** [AdvancedPlugins/Seasons#110]
### Describe the bug

Sometimes AdvancedSeasons creates snow which cannot be broken.
It cannot be broken in survival.
It cannot be broken in creative.
It cannot be removed with world edit.
Blocks cannot be placed where the snow is.
It does not disappear in summer.

It's basically forever corrupting the world and the only thing you can do is bury it underground or wash it away with water.

It shows up as minecraft:snow layers:1 but nothing you do can remove it.

No errors.

Present in Spigot 1.20.6, AdvancedSeasons 1.3.2

https://github.com/AdvancedPlugins/Seasons/assets/4374351/2c4b40aa-591a-4620-957b-17c56040bf8a

### How to reproduce

Play the game with seasons enabled.
Break snow until you find snow that cannot be broken.

**Comment by GC-spigot** [comment]
Have you tried relogging? We can't really place blocks that cannot be broken, this seems more like a visual issue. Try relogging, if that does not help try restarting and let me know if any of these helped / it disappeared after

**Comment by Pilvinen** [comment]
> Have you tried relogging? We can't really place blocks that cannot be broken, this seems more like a visual issue. Try relogging, if that does not help try restarting and let me know if any of these helped / it disappeared after

I have. It did not help.

**Comment by Ynverxe** [comment]
It's your problem solved?

**Comment by Pilvinen** [comment]
> Is your problem solved?

On its on? No, I don't think that's generally how things work.

**Comment by Ynverxe** [comment]
It's a very strange bug. Would you be willing to send your server folder to help me find the problem?

**Comment by Pilvinen** [comment]
> It's a very strange bug. Would you be willing to send your server folder to help me find the problem?

No, but I can try to provide more information.

The affected snow layers act like entities almost. When you try to break them you get the combat fatigue indicator which you wouldn't normally get with blocks.

All attempts to break the snow layers are like trying to break air, nothing is happening. They can't be interacted with.

If you break the block below the snow falls, the it still can't be broken.

Using water bucket can get rid of the  water. Also using lava bucket can melt the snow.

You also can't place a block in the same space as the snow.

**Comment by Ynverxe** [comment]
Another hypothesis is that the block is somehow in a state of infinite gravity. That is, it will try to fall all the time even if it is on a block. This state does not allow the block to be broken.
