### ISSUE TITLE
a lot of problems

### ISSUE THREAD

**Issue by davi-fonto** [AdvancedPlugins/Seasons#112]
### Describe the bug

Hi, I'm using the latest version of the plugin (1.3.2) on my PaperMC 1.20.4 server. There are a lot of bugs, the plugin isn't working properly. Here is a list:
- custom day and night length not working
- when it starts raining it keeps raining forever
- seasons don't change automatically (i always have to do the command)
- custom seasons length not working (i put 20 season days and 10 transition days but in the calendar it seems that one season is 3 days long)

### How to reproduce

I don't know how you can reproduce this. I just installed the plugin on the server along with protocollib and nothing works

**Comment by homerek111** [comment]
I agree with raining issue - every single update makes the plugin work worse.

**Comment by Ynverxe** [comment]
> when it starts raining it keeps raining forever

The infinite rain was confirmed and is being fixed.

> custom day and night length not working
> seasons don't change automatically (i always have to do the command)

Those bugs have attempted to reproduce them in a clean environment (PaperMC 1.20.6, ProtocolLib and AE) and they weren't confirmed.

> custom seasons length not working (i put 20 season days and 10 transition days but in the calendar it seems that one season is 3 days long)

This was confirmed and we are working to fix it.
