### ISSUE TITLE
it's keep raining!

### ISSUE THREAD

**Issue by Nibaalxd** [AdvancedPlugins/Seasons#113]
### Describe the bug

the moment i installed this plugin, it keeps raining all time, doesn't matter what i do /weather clear or when i do /advancedseasons weather day paper_1_20_6_2859708 it says it's invalid command. i try to edit the weather file with how much it should rain for each season but nothing works

### How to reproduce

server ver: 1.20.6
paper
latest plugin ver downloaded

**Comment by Ynverxe** [comment]
Fixed on 1.3.3
