### ISSUE TITLE
 Advanced seasons not working with essentials/cmi

### ISSUE THREAD

**Issue by cmongelli** [AdvancedPlugins/Seasons#116]
### Describe the bug

It shows it is installed but nothing is working with Advanced Seasons.  I was told by Moderator Vision to report the issue here so the devs can solve it for me. I tried typing /as addworld world and restarted the server and it still doesn't look like it's working. 

### How to reproduce

Not sure, installed Advanced Seasons along with dependency, it looks like everything is installed properly but plugin doesn't appear to be working or showing up visually. 

### Screenshots / Videos

![pluins1](https://github.com/AdvancedPlugins/Seasons/assets/56177684/39070d63-a375-49d1-a3dc-6576ee26cba7)
![pluins2](https://github.com/AdvancedPlugins/Seasons/assets/56177684/f7834241-7ae9-4a76-ad85-a2c43d47d67a)

**Comment by cmongelli** [comment]
Can someone please help with this issue I am experiencing?

**Comment by SirJben** [comment]
Hii @cmongelli provide your startup log.

**Comment by cmongelli** [comment]
Hi @SirJben sorry for the delay. Where exactly can I find the startup log to share with you?

**Comment by cmongelli** [comment]
> Hii @cmongelli provide your startup log.

Could you please tell me where I can find that so I can share it?

**Comment by SirJben** [comment]
You can paste the file here with https://mcpaste.io/ or open a Discord Ticket and tag me there.

**Comment by cmongelli** [comment]
Where do I find that file to paste?

**Comment by cmongelli** [comment]
@Ynverxe @SirJben Not sure if I did it correctly or with the correct latest log but I pasted it to the mcpaste.io. This is what I found off our server in the logs folder. Please let me know if there is anything else I need to do. Thank you for the help!

**Comment by Ynverxe** [comment]
You need to past the log in mcpaste.io, save the past and copy the link of your browser and paste the link here.
