### ISSUE TITLE
More features to the API

### ISSUE THREAD

**Issue by Pilvinen** [AdvancedPlugins/Seasons#125]
### Describe the feature

I have two feature requests for the AdvancedSeasons developer API:

**1) Expose the information in the API whether the a biome should get snow during the cold season.**

I built my own system on top of AdvancedSeasons which simulates the vanilla snow accumulation behavior in all biomes, but currently I can't check whether it should snow in biome X. I could do it by manually defining that information for all the biomes in code, but it would be much more convenient to get that information from AdvancedSeasons directly.

**2) Expose block or biome temperature(s) in the API. Currently only getting the temperature for the _player_ is supported.**

This would allow me to check if the block or biome temperature allows snow formation. MC exposes block temperature, but I dabbled with it and  it doesn't really seem to do me much good with AdvancedSeasons.

I suspect you might already have all this information easily available in AdvancedSeasons and would be just a matter of taking a few minutes to expose it in the API and updating the docs.

Thanks for considering this.

**Comment by Ynverxe** [comment]
The first feature can be added easily, but the second may take more time. AS calculates the temperature only for the player, not for blocks or other entities. This is because AS take advantage of the light level to calculate the temperature.

However, we are planned to improve this mechanism to the future.

**Comment by Ynverxe** [comment]
Done!
