### ISSUE TITLE
Armor should warm the player (at least leather armor)

### ISSUE THREAD

**Issue by EmanuelNorsk** [AdvancedPlugins/Seasons#13]
### Describe the feature

It would be cool if armor gives the player heat, similar to clothes in real life. It would be best if at least leather is the best at doing this, for obvious reasons.

**Comment by Mitality** [comment]
Would also be great if we had the option to make netherite armor help players survive extreme heat or something like that... Maybe add an armor-count placeholder for every armor type in the temperature formula, and/or allow us to define conditions for temperature events (e.g. if a player has full netherite armor, trigger heatstroke 10 degrees later / higher)
