### ISSUE TITLE
Terralith Support not exactly working

### ISSUE THREAD

**Issue by TicTecOfficial** [AdvancedPlugins/Seasons#134]
### Describe the bug

every terralith-related biome shows a warning that goes by "minecraft:(TERRALITH_BIOME_NAME) doesn't match with any loaded biome

the rest, my friend, is history.

### How to reproduce

- use the latest advancedseasons
- copy terralith biome config files and replace old ones
- done

### Server Log

https://mcpaste.io/51ba5f3b5a01e8ee

**Comment by Blaezex** [comment]
The terralith biome configuration on this github repo is outdated and the syntax in the latest version of advanced seasons for adding custom biomes has changed.

You can use my terralith config if you want and see if it works.
[biomeConfiguration.zip](https://github.com/user-attachments/files/16395521/biomeConfiguration.zip)

You should be able to replace your existing ones if you are using the latest version of advanced seasons and terralith. It works for me in combination with terralith and terratonic.

**Comment by TicTecOfficial** [comment]
hey man, thanks for replying, this solution worked out really well for me, and i think you could pitch this to the advancedseasons devs to update their terralith integration. closing this issue now

> The terralith biome configuration on this github repo is outdated and the syntax in the latest version of advanced seasons for adding custom biomes has changed.
> 
> You can use my terralith config if you want and see if it works. [biomeConfiguration.zip](https://github.com/user-attachments/files/16395521/biomeConfiguration.zip)
> 
> You should be able to replace your existing ones if you are using the latest version of advanced seasons and terralith. It works for me in combination with terralith and terratonic.

**Comment by TicTecOfficial** [comment]
hey mate, though the server does not include any more warnings none of terralith's biomes are affected by season whatsoever, and they identify as normal biomes (e.g. forests, etc)

**Comment by TicTecOfficial** [comment]
![image](https://github.com/user-attachments/assets/c5e5aca6-32ca-4b7e-ba23-00808be066de)
on the left is a terralith biome, on the right is a regular/advancedseasons biome

**Comment by Blaezex** [comment]
Not really sure if there is much 'we' (the purchasers) can do about it. The biomes are added correctly so I guess this is something that the developer might need to fix.

I only mainly the tested the part myself for the biomes where I would expect snow. As I wasn't getting any snow in my terralith biomes. Now I have snow but instead of the visually snowing its raining (logged a separate issue for that one)

Guess our only option now is to wait till it gets fixed.

**Comment by TicTecOfficial** [comment]
> You can try tweaking around the biome configurations a bit to ensure the left and right biome are in the same configuration file (as there might be some nuances in block coloring) the terralith temperate highlands should be in the forests.yml (not sure what the right biome is?)

hi again, for me snow does appear correctly on terralith biomes, however the grass doesn't turn gray as expected in vanilla biomes.

i've tried to tinker around with the biome configuration files and nothing seems to have worked. the left and the right biomes are not in the same configuration file but it doesn't make much sense to me. can't we make it so that every single biome in a world changes colour/seasons properly?

**Comment by GC-spigot** [comment]
Hi! It was working previously as we tested, but we will test and update everything so terralith works correctly with us again :) On 2 Aug 2024, at 5:25 AM, Eden Koper ***@***.***> wrote:﻿

You can try tweaking around the biome configurations a bit to ensure the left and right biome are in the same configuration file (as there might be some nuances in block coloring) the terralith temperate highlands should be in the forests.yml (not sure what the right biome is?)

hi again, for me snow does appear correctly on terralith biomes, however the grass doesn't turn gray as expected in vanilla biomes.
i've tried to tinker around with the biome configuration files and nothing seems to have worked. the left and the right biomes are not in the same configuration file but it doesn't make much sense to me. can't we make it so that every single biome in a world changes colour/seasons properly?

**Comment by TicTecOfficial** [comment]
ah sweet, thanks for reaching out! i'll be looking forward to this :D

**Comment by Ynverxe** [comment]
Hi! I updated the terralith biome files. So if you put it in your biomeConfiguration folder you should stop seeing that message.

**Comment by TicTecOfficial** [comment]
> Hi! I updated the terralith biome files. So if you put it in your biomeConfiguration folder you should stop seeing that message.

hi! i've already had that part sorted out, the current problem is that season changes aren't being reflected on specifically terralith biomes only. but they work completely fine on vanillas biomes

**Comment by Ynverxe** [comment]
> > Hi! I updated the terralith biome files. So if you put it in your biomeConfiguration folder you should stop seeing that message.
> 
> hi! i've already had that part sorted out, the current problem is that season changes aren't being reflected on specifically terralith biomes only. but they work completely fine on vanillas biomes
> 
> this is mentioned on the image shown above if you scroll up a bit

Your biome isn't being converted into an AS biome. For example, if you have terralith:temperate_highlands configured into the biomeConfiguration/forest.yml you should see something like advancedseasons:forest_spring_0.

The conversion works fine when the terrain is being generated, but seems that it doesn't works with already generated terrain. I will work on this.

**Comment by TicTecOfficial** [comment]
> > > Hi! I updated the terralith biome files. So if you put it in your biomeConfiguration folder you should stop seeing that message.
> > 
> > 
> > hi! i've already had that part sorted out, the current problem is that season changes aren't being reflected on specifically terralith biomes only. but they work completely fine on vanillas biomes
> > this is mentioned on the image shown above if you scroll up a bit
> 
> Your biome isn't being converted into an AS biome. For example, if you have terralith:temperate_highlands configured into the biomeConfiguration/forest.yml you should see something like advancedseasons:forest_spring_0.
> 
> The conversion works fine when the terrain is being generated, but seems that it doesn't works with already generated terrain. I will work on this.

awesome! let me know once again when you have this worked on

**Comment by Ynverxe** [comment]
Should be solved in the next release.
