### ISSUE TITLE
"Incorrect Argument for command" error occurs everytime an event item is attempting to be given out

### ISSUE THREAD

**Issue by TicTecOfficial** [AdvancedPlugins/Seasons#135]
### Describe the bug

everytime there's a new event (e.g. New Years Celebration) the plugin automatically gives an item(as expected) but it seems like there is something wrong with the commands as they can't be carried out correctly. 

it seems it may be related to the naming of the items where it is failing

### How to reproduce

- advanced seasons on 1.21
- set to any seasonal event
- bam

**Comment by TicTecOfficial** [comment]
an example of the command in question: give %player% cookie 1 **name:&2Christmas_Treat**

**Comment by Ynverxe** [comment]
Those commands are stored in events.yml. I uploaded the fixes.
