### ISSUE TITLE
placeholder not working

### ISSUE THREAD

**Issue by efor89** [AdvancedPlugins/Seasons#137]
### Describe the bug

i try this 2 placeholder but they dont work for me.
%advancedseasons_season_next%
%advancedseasons_season_remainingdays%

### How to reproduce

1. use TAB for scoreboard
2. set in scoreboard the placeholder
3. start server and join(paper server 1.21)
4. placeholder = N/A

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/113c5570-546d-4583-a24d-824be4342cd5)

**Comment by Ynverxe** [comment]
Hi! After the "..._season" you need to add a world name or just use "current" to display information about the current player's world.

Like this:
![imagen](https://github.com/user-attachments/assets/fa74d762-d61d-479b-84b1-e44c589bfaf7)

**Comment by Ynverxe** [comment]
Hi! You need to add a world name after the "..._season".

Like this:
![imagen](https://github.com/user-attachments/assets/e55fdebd-faef-46e7-8548-3010b5249e70)
