### ISSUE TITLE
Fahrenheit display with Celsius enabled

### ISSUE THREAD

**Issue by homerek111** [AdvancedPlugins/Seasons#138]
### Describe the bug

One of my players has fahrenheit as his temperature unit...
What's weired that in settings it is set to false + all other players have Celsius (only 1 player has Fahrenheits..)

convertToFahrenheit: false

![obraz](https://github.com/user-attachments/assets/24b2dd2c-e221-482d-97e1-cf9a5638c883)

### How to reproduce

using the latest version 1.3.14

**Comment by Ynverxe** [comment]
Was this issue fixed on 1.4.3?

**Comment by homerek111** [comment]
> Was this issue fixed on 1.4.3?

No idea as it happened only to one of my players and I couldn’t replicate it myself
