### ISSUE TITLE
Sleeping needs some tweaks

### ISSUE THREAD

**Issue by purejosh** [AdvancedPlugins/Seasons#14]
### Describe the bug

Hello! I had time to install v1.0.3, and noticed that the sleeping felt a little unusual. This is due to the duration of the sleep, as well as the time the player wakes up. 
In Vanilla, the player can sleep as early as 6:32pm, sleeps for 101 ticks, and then wakes up with the server fast forwarded to 6:00am.
With this plugin installed, the player can sleep as early as 6:12pm, sleeps for ~40 ticks, and then wakes up with the server fast forwarded to 7:00am. 
There's actually very detailed information about the sleeping cycle in the minecraft wiki. https://minecraft.wiki/w/Bed#Sleeping

Can the sleeping behaviors be adjusted to feel more natural? 

### How to reproduce

Sleeping in a bed on a vanilla world, vs sleeping in a bed on a server with AS installed. 

### Screenshots / Videos

Vanilla
https://github.com/AdvancedPlugins/Seasons/assets/70633949/11d16cf2-6064-4b73-a134-21e371605586

AS installed server
https://github.com/AdvancedPlugins/Seasons/assets/70633949/f4ded550-fbbc-4dfd-a598-851fb1a64cef

**Comment by GC-spigot** [comment]
Sure I'll look into this. Problem is that the worlds have `doDaylightCycle` set to false, so it completely disables sleeping. This plugin is now basically manual overriding sleep. 

The start of sleeping time is actually handled by minecraft, we check if player is allowed to sleep. Weird that it lets them sleep early. I'll adjust sleep time (in bed) and what time it's forwarded to. Thanks for the report!
