### ISSUE TITLE
Conflict with sleep plugin and blocking /time command

### ISSUE THREAD

**Issue by deangnjidic** [AdvancedPlugins/Seasons#142]
### Describe the bug

It started after updates on friday. Went through a lot of testing what is causing it and ended up deleteing AS and after that sleep plugin and /time started working without issues.

### How to reproduce

Install Sleep Most plugin

**Comment by Ynverxe** [comment]
Version?

**Comment by deangnjidic** [comment]
Sleep Most latest. 

It happened on AS 1.4.0 now when it was reverted to pre 1.4.0 works fine

**Comment by Ynverxe** [comment]
> Sleep Most latest.
> 
> It happened on AS 1.4.0 now when it was reverted to pre 1.4.0 works fine

Ok, is there another problem or is that all?

**Comment by deangnjidic** [comment]
Yeah that all

**Comment by mrgeneralq** [comment]
@deangnjidic , I am the dev of sleep most. Let me know if I can be of any help to address this issue.
