### ISSUE TITLE
/gamerule playersSleepingPercentage <value> not supported

### ISSUE THREAD

**Issue by EmreSoftware** [AdvancedPlugins/Seasons#143]
### Describe the bug

When I change the game rule
/gamerule playersSleepingPercentage <value>
It doesn't apply to the plugin and wont let the world skip a day.

### How to reproduce

Change the gamerule
/gamerule playersSleepingPercentage <value>
Try to sleep according to the value
You'll wake up and it says day's been skipped but it's still night.

**Comment by Ynverxe** [comment]
Hi! I'll work on this. This is more a feature for compatibility with the gamerule than a bug.

**Comment by Ynverxe** [comment]
Fixed. Wait for the next release.

**Comment by EmreSoftware** [comment]
Thank you!
