### ISSUE TITLE
After downloading the latest version of the plugin. The plugin does not start and crashes.

### ISSUE THREAD

**Issue by TobiTakToRobi** [AdvancedPlugins/Seasons#144]
### Describe the bug

![image](https://github.com/user-attachments/assets/707e1866-e301-4b3a-9fd1-fd061f08de2f)
![image](https://github.com/user-attachments/assets/62ca2b1a-0372-4219-9cfb-9d2a4a904b63)
![image](https://github.com/user-attachments/assets/89772780-4e29-4d03-8ec4-1989d9100ac8)

### How to reproduce

All you need to do is upload the plugin.

**Comment by Ynverxe** [comment]
The problem here is that the java version which your server was compiled is < Java 21.

* Update your minecraft server version to 1.20.6 or major.
* Compile your server jar with java 21.

**Comment by Ynverxe** [comment]
> I have java 21 and my server version is 1.20

Mojang started using Java 21 on 1.20.5. I compiled Spigot 1.20 using Java 21 with BuildTools, you can try this or use a newer MC version.
