### ISSUE TITLE
Placeholder %advancedseasons_season_<world>%

### ISSUE THREAD

**Issue by nonsonoanto** [AdvancedPlugins/Seasons#148]
### Describe the feature

A placeholder that can retrieve the season of another world

**Comment by Ynverxe** [comment]
This is exactly how the season placeholder works right now.

**Comment by nonsonoanto** [comment]
yeah, but you can't retrieve the season information of an another world, with this you can access the season of the gameplay world everywhere, even at spawn

**Comment by nonsonoanto** [comment]
> This is exactly how the season placeholder works right now.

yeah, but you can't retrieve the season information of an another world, with this you can access the season of the gameplay world everywhere, even at spawn

**Comment by nonsonoanto** [comment]
my bad, didn't see that
