### ISSUE TITLE
Seasons Pause Progression Inoperative

### ISSUE THREAD

**Issue by dtawales** [AdvancedPlugins/Seasons#150]
### Describe the bug

V: 1.20.1 Paper
P: AdvancedSeasons-1.4.3
The pause season progression mechanic does not work. 

Turning the setting to True in the calendar config and reloading AND restarting the server does nothing. In the previous version I had, setting it to paused would generate exceptions multiple times a second in the server console, since updating to latest it no longer generates exceptions, but still does not function as intended.

I paid for this plugin some time ago and it is supposed to be an integral part of the server that opened last week, seeing 30-35 concurrent players at any given time, but has been disabled now for days. Discord support was not helpful. 

### How to reproduce

1. Set season progression to paused in config
2. Wait for the correct amount of days to progress, the season will change. 
3. Reinstall, reconfig, and reload, the seasons still change.

**Comment by dtawales** [comment]
Are there any known workarounds to this?

**Comment by Ynverxe** [comment]
> Are there any known workarounds to this?

Yes, fixed. Wait for the next release!
