### ISSUE TITLE
Rain issues

### ISSUE THREAD

**Issue by stski121** [AdvancedPlugins/Seasons#151]
### Describe the bug

2 issues i have with rain at the moment, 1 is happening on both bedrock and java clients, it rains for a few seconds, then stops for a few seconds then repeats, so its basically a constant rain on/off. Disabling the weather in the config stops the issue. If disabled while its raining, the rain remains (which shows that its not something else clearing the weather every few seconds etc).

The other issue i have is with bedrock clients,  the snow appears as rain, where on java it appears as snow(in the same location). Not sure if this is a limitation of geyser or something that can be fixed.

### How to reproduce

For the first issue just enable the plugin and enable custom weather.
My current weather values are: 
Spring: 50
Summer: 10
Fall: 60
Winter: 80
in case it somehow matters.

For the second issue, enable the turn rain to snow setting for a biome that otherwise doesn't snow, and check from bedrock client during winter season. The snow and freezing appears normally, but the snowfall is still just rain.
Running latest paper and geyser versions as well as latest A.S from spigot

**Comment by Ynverxe** [comment]
AS tries checks if the chances of raining passes or not every 20 seconds, maybe that's your problem and can be solved adding a setting to customize this cycle length. 
Regarding to the snow issue, maybe a Geyser problem, AS doesn't handles bedrock players.
