### ISSUE TITLE
Seasons mobs.yml spawns mobs inside worldguard regions

### ISSUE THREAD

**Issue by Vehzx** [AdvancedPlugins/Seasons#156]
### Describe the bug

The mobs.yml that is used to spawn different mobs near the player depending on the season is spawning mobs inside worldguard protected regions.

I believe this is because in worldguard config, I have "allow-plugin-spawning" set to true, which allows plugins to spawn mobs inside the regions. I use this because of advancedpets, allowing player pets to go to spawn and other regions that are protected from worldguard regions, even though those regions have mob-spawning flag set to deny.

Seasons is spawning mobs from the yml into spawn, meaning there are mobs such as spiders, witches and other hostile mobs spawning in spawn.

I'm almost certain seasons is causing this, as I have uninstalled the jar and restarted my server, to find no mobs in spawn, and no mobs spawning in spawn.

AdvancedMobs also has this issue with custom mobs spawning in worldguard regions, and i've made a github post there about it.

### How to reproduce

Get the following plugins (not sure if worldedit has anything to with it, but just to be sure):

Worldguard version: 7.0.11-SNAPSHOT
Worldedit version: 7.3.6
Seasons version: 1.4.6

server jar: paper-1.21.1-74

1. Create a worldguarded region, set the mob-spawning flag to deny.
2. Go into the worldguard config, and set "allow-plugin-spawning" to true.
3. Restart server and just wait for seasons to spawn mobs (I always set the season to fall to test this, as it spawns witches, spiders etc).

As a temporary solution i've just set the mobs.yml "enabled" to false, but I do hope to use this feature in the future if you can replicate and fix this.

### Server Log

https://mcpaste.io/523b2b974bddcf77

**Comment by Ynverxe** [comment]
Fixed! Wait for the next version.
