### ISSUE TITLE
Seasons breaks and doesn't load on 1.4.12

### ISSUE THREAD

**Issue by Vehzx** [AdvancedPlugins/Seasons#157]
### Describe the bug

When using the latest seasons jar, I get the follow error spammed in my console, and the plugin ceases to function. This spamming error only starts happening once a player joins the server (if that helps at all).
https://mcpaste.io/e411917bb1f7e012

On startup, this error is given when the plugin loads.
https://mcpaste.io/8aba73d2eea4e284

I had a ticket in the discord with Jben incase you need to look at it - #seasons-sirjben-0251 I was told to forward it to github.

### How to reproduce

I don't actually know how to reproduce, Jben is the one that managed to do that, however he said in the ticket it looks like server compatibility issue.

This was running:
Seasons 1.4.12 on Paper 1.21.1-57-b483da4 (MC: 1.21.1)

### Server Log

https://mcpaste.io/9218c89664313cd1

**Comment by Vehzx** [comment]
ticke transcript: https://tickettool.xyz/transcript/v1/867844144696655895/1285977306481033227/transcript-seasons-sirjben-0251.html/66ec3b32/66eae9b2/078800deb8926f9f09c0f868acf382c935b52221a402b70ee5303399ff460a01

**Comment by SirJben** [comment]
Update your plugin: https://advancedplugins.net/item/185/updates
