### ISSUE TITLE
Advanced Season is not working

### ISSUE THREAD

**Issue by catlegacy** [AdvancedPlugins/Seasons#158]
### Describe the bug

the plugin have error at the start im using latest mc server and latest seasons plugin

### How to reproduce

idk how 
but Jben said its compatibility issue on 1.21.1

### Screenshots / Videos

https://prnt.sc/WIA-IIhKONEU

### Server Log

https://mcpaste.io/0fb08e856dd316f0

**Comment by SirJben** [comment]
Update your plugin: https://advancedplugins.net/item/185/updates
