### ISSUE TITLE
Too many animals spawned in the cave

### ISSUE THREAD

**Issue by LovelyGuYiMeng** [AdvancedPlugins/Seasons#16]
### Describe the bug

AdvancedSeasons 1.0.6
1.20.2 purpur 2095
Too many animals spawned in the cave
Seasonal Animal spawn Global Settings Invalid

### How to reproduce

When seasonal animals are enabled，Animals will spawn indefinitely in any burrow underground.
When I turn off Seasonal Animal，Animals will still spawn.

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Seasons/assets/76251800/17b19541-3f43-4e37-9065-c07e5e196202)

**Comment by GC-spigot** [comment]
Okay so from testing I recommend you just update mobs.yml to lower `chance` value to like `3`

**Comment by LovelyGuYiMeng** [comment]
> 好的，根据测试，我建议您只需将 mobs.yml 更新为较低的`chance`值即可`3`

I don't think this way can completely solve this problem, because animals will still be spawned in caves, and it is extremely unreasonable for animals to be spawned in caves.
