### ISSUE TITLE
Error messages in console

### ISSUE THREAD

**Issue by mellowism** [AdvancedPlugins/Seasons#160]
### Describe the bug

The plugin doesn't load, and now I have eternal winter and can't get the ice on lakes to disappear.

### How to reproduce

Just load the plugin with my other plugins

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/9311d7ba-c8e9-4d67-bd35-d5a9129baf7d)

### Server Log

https://mcpaste.io/2fbe7e083136540f

**Comment by QuartzWarrior** [comment]
seems to be a recurring error with version 1.21, where the plugin fail to operate despite claims of compatibility. It appears that, contrary to previous assurances, these plugins are not fully supported on version 1.21.

**Comment by SirJben** [comment]
Update your plugin https://advancedplugins.net/item/185/updates
