### ISSUE TITLE
Paper: After update new situation 1.21.1 Version 98

### ISSUE THREAD

**Issue by Stormbold** [AdvancedPlugins/Seasons#161]
### Describe the bug

No active world added
Folder already deleted and renewed
Jar file removed and the latest version added.

Unfortunately still no possibility to use the plugin

### How to reproduce

Paper: 1.21.1 Version 98

### Screenshots / Videos

https://ibb.co/2ntfTqv

### Server Log

https://mcpaste.io/696cdab355ca07bf

**Comment by SirJben** [comment]
Update your plugin. https://advancedplugins.net/item/185/updates
