### ISSUE TITLE
Plugin does not work

### ISSUE THREAD

**Issue by KonradKoriander** [AdvancedPlugins/Seasons#163]
### Describe the bug

The plugin and all of its features do not work on my 1.21.1 PaperMC server. I get a message in the chat telling me that this has occured due to "errors". 

### How to reproduce

Follow the given instruction on the wiki of the plugin step by step.

### Screenshots / Videos

![popo](https://github.com/user-attachments/assets/ddb5dd56-f0fc-4392-8051-54085b6ebbb1)
![kaka](https://github.com/user-attachments/assets/88d4a2e0-3d0a-4772-a5db-04e59c6e5a22)

**Comment by SirJben** [comment]
Update your plugin. https://advancedplugins.net/item/185/updates
