### ISSUE TITLE
SuperiorSkyblock

### ISSUE THREAD

**Issue by Xitryne** [AdvancedPlugins/Seasons#168]
### Describe the bug

Snow does not appear on the ground when it snows, I have tried to modify the options in the files, I have tried several, with or without, but nothing works. It must be related to the terrain protection I suppose?

### How to reproduce

^^^^

**Comment by Ynverxe** [comment]
Seasons prevents ice and snow generation on protected areas.

![Here is a list of supported protection plugins](https://github.com/user-attachments/assets/b1b8b97d-8ab3-46b4-a444-34515ea07b41)
