### ISSUE TITLE
Using /as info fails

### ISSUE THREAD

**Issue by purejosh** [AdvancedPlugins/Seasons#17]
### Describe the bug

Using `/as info` produces an error in game, when using 1.0.9. There may be other commands failing, too. 

### How to reproduce

Use `/as info` in game. 

### Server Log

https://gist.github.com/purejosh/3191b361df038d0d999e893214153f57

**Comment by GC-spigot** [comment]
Either world or biome is not enabled with seasons, ill add a proper warning message
