### ISSUE TITLE
Temperature Events doesn't work when using AdvancedSeasons 1.5.1

### ISSUE THREAD

**Issue by Tenitrex** [AdvancedPlugins/Seasons#175]
### Describe the bug

Couple hours ago i installed AdvancedSeasons 1.5.1 on minecraft purpur 1.21.1 server and temperature effects doesn't seem to work basically no freezing, sweating etc.. Everything in the configs is default however i managed to fix this issue when downgrading to 1.5.0

Also seasons 1.5.1 starts normally no console errors

### How to reproduce

My setup

1# Mc server running purpur build #2324 1.21.1
2# AdvancedSeasons 1.5.1 and default config

**Comment by GC-spigot** [comment]
Fixed for an update soon!
