### ISSUE TITLE
Temperature effects are not working - Advanced Seasons 1.5.1 - Paper 1.21

### ISSUE THREAD

**Issue by Vissha47** [AdvancedPlugins/Seasons#176]
### Describe the bug

Everything else works correctly, it shows the temperature but when I get the subtitle saying ‘you are freezing’ for example, nothing happens, and so on with all the effects.

### How to reproduce

I don't know, I just installed the plugin and protocollib, and then I tried the features and then I realised that they were not working.

### Server Log

https://mcpaste.io/3625426b1b3cc4c2

**Comment by Tenitrex** [comment]
Yes i reported it before, if you need a quick fix i suggest using 1.5.0

**Comment by Vissha47** [comment]
> Yes i reported it before, if you need a quick fix i suggest using 1.5.0

ooh thanks, but how do I download an older version?

**Comment by Tenitrex** [comment]
Go to Advanced Seasons spigot page, and in the menu select > version history

**Comment by GC-spigot** [comment]
Fixed for an update soon!
