### ISSUE TITLE
Ideas for smoothing out rain

### ISSUE THREAD

**Issue by purejosh** [AdvancedPlugins/Seasons#18]
### Describe the feature

It's hard to hit a perfect ratio for rain, but I'm thinking the checks might just be too frequent. Even at 10%, the server rains for 20 seconds and stops for maybe a few minutes, which is more than vanilla, so there might just be some tweaking needed. 

Maybe changing the checks to once every 2 minutes, since the daytime is 10 minutes. If the check passes, allow it to rain for 4 minutes and don't check again after that rain cycle for 4 more minutes. This would ensure an immunity after the rain cycle, preventing it from being too rainy. 

Or, maybe instead of a percentage, there could be a scale of 1 though 10 for rain aggressiveness. The rain aggressiveness settings can be tweaked on the back end, for even more behavior. For example: 

`rainAggressiveness: 1` = rain check every 10 minutes, rains for 2 minutes, immunity for 20 minutes
`rainAggressiveness: 10` = rain check every 1 minute, rain for 6 minutes, immunity for 4 minutes. 

And rainAggressiveness would be an individual season setting, which paired with the chance to rain, can provide more finite control of the rain patterns. I personally like winter with a lot of precipitation, but summer showers are also nice to have too, but in both cases, I would want the rain to be more consistent and not triggering every 20 seconds and raining for only 20 seconds. 

Let me know your thoughts! Here to help.

**Comment by GC-spigot** [comment]
It's 20 seconds because of the vast range of day length it can be, from 1 minute to 20. This would handle the minute length days fine as well.

What about a solution that instead of every 20 seconds it checks 4 times per day? This wouldnt make the rain feel so random.

**Comment by Mitality** [comment]
Would be a great feature - I just experienced a 20s thunderstorm 😅

**Comment by Mitality** [comment]
Also, in terms of smoothing out things... I do not use snow and ice myself, however I feel like it would make much more sense to have it spread with an algorithm like this: 
![0d591f925c12670ec8e7ed60ede97af706db451a](https://github.com/AdvancedPlugins/Seasons/assets/96748385/b88265dc-0491-46c5-8901-2cb5f96b9fb5)
