### ISSUE TITLE
AS not working

### ISSUE THREAD

**Issue by Sweetwitchserver** [AdvancedPlugins/Seasons#189]
### Describe the bug

The plugin just stopped working, just for changes I made the calendar a little longer for the change in weather and it worked fine. I just added an AxCalendar plugin | Customizable Advent Calendar and it stopped working

### How to reproduce

The plugin just stopped working, just for changes I made the calendar a little longer for the change in weather and it worked fine. I just added an AxCalendar plugin | Customizable Advent Calendar and it stopped working

### Screenshots / Videos

![2024-11-30_16 10 23](https://github.com/user-attachments/assets/e5274e11-8e46-4986-8d82-2da76c8d1e73)
![2024-11-30_16 12 57](https://github.com/user-attachments/assets/f8227d40-2a67-4263-bb5a-28a5bbfe0967)

**Comment by Sweetwitchserver** [comment]
![image](https://github.com/user-attachments/assets/2ed2356f-79b7-4c20-a31b-70f43c659d39)

**Comment by GC-spigot** [comment]
Hi, you must provide the server log which would let us diagnose your issues. It's located in `logs` folder, will be called `latest`.
