### ISSUE TITLE
Sleeping stops working after a couple nights

### ISSUE THREAD

**Issue by purejosh** [AdvancedPlugins/Seasons#20]
### Describe the bug

I'm not sure what's triggering it to break, but after a couple days go by, we're no longer able to sleep the night away. We'll still jump into bed and sleep, but the night doesn't skip to daytime. 

### How to reproduce

I'm not sure how to reproduce it, to be honest, but it does work right after a restart. There's no log lines in the console to help understand what's happening. Time is moving along per usual. I'm using v1.0.10 on purpur 1.20.1. 

### Screenshots / Videos

https://github.com/AdvancedPlugins/Seasons/assets/70633949/d602b28e-5675-44ae-ad0e-4add928197ed

**Comment by purejosh** [comment]
Just upgraded to 1.0.12, I'll report if it comes back.

**Comment by purejosh** [comment]
Still happening on 1.0.12.

**Comment by Gresakm** [comment]
it's also happening to me on 1.0.16

**Comment by GC-spigot** [comment]
This is actually something with essentials / cmi plugin. They have a permission for players to not be required to be sleeping for time to skip, so its broken because of this. Im looking into working together with that feature.
