### ISSUE TITLE
Season duration and transition not working as expected

### ISSUE THREAD

**Issue by QuartzWarrior** [AdvancedPlugins/Seasons#24]
### Describe the bug

I am using the AdvancedSeasons plugin to create dynamic seasons in my Minecraft server. I want to make each season last 84 in-game days and each transition period last 42 in-game days, which would add up to 504 in-game days per year. However, I am facing some issues with the plugin.

- When changing season-druation or transition values, the current month is not displayed in the calendar gui.
- The nextseason command does not change the season correctly.

### How to reproduce

1. Install the AdvancedSeasons plugin on your server and restart it.
2. Open the calendar.yml file and change the seasonDays to 84 and the transitionDays to 42.
3. Join the server and type /calendar to open the calendar GUI. Notice that the GUI shows May as the current month, even though it should be January.
4. Type /nextseason to advance the season. Notice that the GUI still shows May as the current month, even though it should be February.
5. Repeat step 4 until you reach the end of the year. Notice that the GUI never changes the month or the season, and always shows May or September.

### Screenshots / Videos

Before changing season-duration / transition values: https://media.discordapp.net/attachments/1198739680900960328/1198758727751319672/image.png?quality=lossless
After changing them: https://media.discordapp.net/attachments/1198739680900960328/1198752335246135376/image.png?quality=lossless

**Comment by GC-spigot** [comment]
Confirmed issue, will be fixed next update. Thanks for reporting!
