### ISSUE TITLE
Effects of seasonal weather effecting Staff in vanish.

### ISSUE THREAD

**Issue by Skippy8787** [AdvancedPlugins/Seasons#25]
### Describe the bug

When staff go into vanish the effects of things like sweating/heatstroke/nausea and stuff are still prevelent meaning the staff cannot obtain visually unobstructed recordind for use in tickets. 

### How to reproduce

Using premium vanish, go into /vanish effects of the seasons weather are still viasble. 

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Seasons/assets/108057642/e9005df5-d26e-4c47-96b5-bf41d0452fd9)

**Comment by GC-spigot** [comment]
Thanks looking into this

**Comment by GC-spigot** [comment]
Fixed
