### ISSUE TITLE
Seasonal Mob Spawning Issue

### ISSUE THREAD

**Issue by DanalBopper** [AdvancedPlugins/Seasons#26]
### Describe the bug

It seems as though that the seasonal mob spawning, even though I have it disabled, changes the biome of air blocks and some surface blocks in caves deep underground and spawns a lot of mobs and snow underground. I do have my seasons modified to be 6 days in length and changed the day length from 20 real minutes to 30 minutes (via Advanced Seasons).

I have had the seasonal mobs spawning disabled for a week or so and went on an entity clearing spree and went back to the same caves to see them chock full of mobs again which suggests that toggling that option off does not work. 

### How to reproduce

Paper 1.20.4 server; latest Advanced Seasons. 

### Screenshots / Videos

https://i.imgur.com/CGHsWR5.jpeg 
https://i.imgur.com/GCL9oBM.jpeg

### Server Log

N/A

**Comment by GC-spigot** [comment]
Should be solved now
