### ISSUE TITLE
Problem with /sit

### ISSUE THREAD

**Issue by Ferippu** [AdvancedPlugins/Seasons#27]
### Describe the bug

When a player uses the /sit command or sits on a ladder, their temperature begins to decrease non-stop until they freeze.

### How to reproduce

 use the /sit command or sits on a ladder.

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Seasons/assets/157979455/5473c9d7-732c-400f-8112-bd8e9b919bf2)
![image](https://github.com/AdvancedPlugins/Seasons/assets/157979455/db5f7eba-1cbb-44f1-bbd8-0fdbff235e99)

**Comment by GC-spigot** [comment]
Fixed!
