### ISSUE TITLE
Dynmap winter support - some improvement for that

### ISSUE THREAD

**Issue by homerek111** [AdvancedPlugins/Seasons#30]
### Describe the feature

Hello, is it possible to make a winter Dynmap support work in different way than turning off all the renders…? I assume it’s not possible to restrict it to snow only (what is misswritten on your wiki and you should change that…) but maybe some other way to keep winter renders available and avoid „griefing” the Dynmap with random snow chunks

**Comment by GC-spigot** [comment]
Hey its not possible unfortunately from our end, and getting a request through to them is as impossible. Ill think of what we could do but likely this is the only way

**Comment by homerek111** [comment]
> Hey its not possible unfortunately from our end, and getting a request through to them is as impossible. Ill think of what we could do but likely this is the only way

I was thinking about it and I have some idea… I don’t know if it might be useful but maybe you can find some application for it.

Dynmap has an option to use texturepacks…
What if there would be some texturepack with INVISIBLE SNOW TEXTURE activated in the winter??? 

The problem might come with normal snow on the map (on real Minecraft snow biomes)… but maybe it wouldn’t be that bad to make snow invisible and keep snow_block visible

I have no idea if texturepack idea is technically possible to do - but maybe it can help you finding a solution somehow…

**Comment by GC-spigot** [comment]
We'll look into what we can do, there's a few dynmap suggestions open, ill bunch all of them into one. Thanks for the suggestion!
