### ISSUE TITLE
grief defender support

### ISSUE THREAD

**Issue by ianflig** [AdvancedPlugins/Seasons#31]
### Describe the feature

add compatibility with grief defender claims, for example when winter arrives, advancedseasons generates ice on it, still having "ice-growth" denied flag

**Comment by TheTechnologyStudio** [comment]
I second this feature

**Comment by GC-spigot** [comment]
Added this, however I couldn't test it because it's a paid plugin. Let me know if this works / doesnt work in next update, thanks!
