### ISSUE TITLE
The time of the world does not pass properly.

### ISSUE THREAD

**Issue by Ferippu** [AdvancedPlugins/Seasons#34]
### Describe the bug

The time is set to last 120 minutes, however the time is lasting like in Vanilla (10/10 minutes). Time is also frozen and to fix this I had to make a Skript to run "/gamerule dodaylightcycle True", however time passes like Vanilla.

### How to reproduce

I've tried all kinds of "time", if it goes over 20 minutes it doesn't work as it should.

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Seasons/assets/157979455/1e247f26-7857-4a41-835f-1ea074ee5de4)

**Comment by GC-spigot** [comment]
Hey, this seems to be working well for us. Are you still having problems? Try restarting :)
