### ISSUE TITLE
Terralith support

### ISSUE THREAD

**Issue by Mitality** [AdvancedPlugins/Seasons#38]
### Describe the feature

I know you're on a trip rn, but if you got time, pls finally do it. I'm looking forward to this so much that I check the relevant ticket on Dc every day to see if anything has happened xd
<img width="292" alt="message" src="https://github.com/AdvancedPlugins/Seasons/assets/96748385/ff1d1386-13d0-4bf0-b39a-bd37f017cd1a">

**Comment by Mitality** [comment]
I know you were away and things get busy, but it's been a month since you said it would be done "today/tomorrow." If you need help or ran into any problems, let me know, perhaps I can help. Although I've never used biomes within a Minecraft Java plugin, it seems doable even for me since there's documentation about it and other plugins like MythicMobs and BiomeManager have done it. Would appreciate if you could at least say something about it...
This is needed for a new gamemode on a private velocity network that is planned to release in 2 months or so. Therefore, it would be great, if you / we could do this until then. Temperatures get so absurd when entering any terralith biome, ice doesn't spread over and so on... If you add nether and end support, there will be another issue with incendium, as temperatures in the nether would go down to default temperature in any custom biome and upon setting the default temperature up high, all custom overworld and end biomes would become hot, so that wouldn't really be an option... This is such a great plugin, but this small feature, just the ability to use custom biomes within the biome configuration (maybe like "terralith:biome_name") is really needed to make it usable with custom worldgeneration... I'm checking for updates on this almost daily since a month now 🥲 PLEASE make somethin work. Ty!

**Comment by GC-spigot** [comment]
Here it is! https://github.com/AdvancedPlugins/Seasons/tree/main/terralith%20configuration
We'll have an update for the plugin later today which will add proper support, so update the plugin and add this configuration!
