### ISSUE TITLE
Snow effect while Winter glitch

### ISSUE THREAD

**Issue by homerek111** [AdvancedPlugins/Seasons#39]
### Describe the bug

Hello, there are some random snow effects around the player while winter - even with high temperature underground...
It happens on positive and negative coordinates (while winter season)

### How to reproduce

wait for winter... and play :PPP
(the newest 1.1.1 version)

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Seasons/assets/93496464/1bbd3aa0-abb6-46d7-b750-dcfddd414e1c)

**Comment by GC-spigot** [comment]
Alright thanks we'll take care of this.
