### ISSUE TITLE
dynmap support

### ISSUE THREAD

**Issue by homerek111** [AdvancedPlugins/Seasons#40]
### Describe the bug

dynmap rendeing is disabled on winter but still it makes my map look terrible... 

in different seasons (not winter) some chunks keep snow until players render it again and dynmap triggers that chunks to render but advanced seasons does not clean them from snow... there must be some way to prevent it from happening :/

### How to reproduce

dynmap + advancedseasons

### Screenshots / Videos

![obraz](https://github.com/AdvancedPlugins/Seasons/assets/93496464/a7d12ec2-3093-493d-b8c3-7ed91301c4a8)

**Comment by TheTechnologyStudio** [comment]
I second this but with bluemap support. Dynmap sucks.

**Comment by GC-spigot** [comment]
Its not possible to do anything without freezing the map unfortunately - I can unfreeze it once the snow is gone. Ill contact the devs but its unlikely that anything is possible.

**Comment by homerek111** [comment]
> Its not possible to do anything without freezing the map unfortunately - I can unfreeze it once the snow is gone. Ill contact the devs but its unlikely that anything is possible.

The problem is that even with freezing there are still issues with that (the screenshot is made in diffferent season than winter - because advancedseasons did not manage to clean that chunks but Dynmap managed to render them)

**Comment by homerek111** [comment]
@GC-spigot by "completed" you mean abandoned or you actually gonna implement it in upcoming updates?
