### ISSUE TITLE
standing in powdered snow + drinking bottle of water

### ISSUE THREAD

**Issue by homerek111** [AdvancedPlugins/Seasons#42]
### Describe the feature

standing in powdered snow could make the temperature go down (while standing in the block)
drinking bottle of water could for example set the temperature to X degrees for Y time (configurable) or at least make it lower for Y time

**Comment by homerek111** [comment]
![2024-02-17_16 02 53](https://github.com/AdvancedPlugins/Seasons/assets/93496464/5de7b4ee-6e34-4372-8f35-fdf0352a2da8)

I add example of no sense situtation with powdered snow (47 degrees and sweating + getting frozen...)

**Comment by GC-spigot** [comment]
Hey, we already have accepted a request for making all of this customisable :) We'll work on adding features like this ASAP!
