### ISSUE TITLE
Performance loss with setting biome for season (see spark report)

### ISSUE THREAD

**Issue by Technofied** [AdvancedPlugins/Seasons#43]
### Describe the bug

Set biome is resource intensive and could be further optimised. See the spark report attached in "PLUGIN" view

### How to reproduce

Use the plugin (I'm not entirely sure how to reproduce)

### Screenshots / Videos

https://spark.lucko.me/RNPJH4AO8f (spark report)

**Comment by GC-spigot** [comment]
It's all done async and does not lag the actual server thread. Are you having TPS or any other issues?

**Comment by GC-spigot** [comment]
I updated a few things for 1.20.4 plugin version, let me know if this helps you.

**Comment by Technofied** [comment]
> I updated a few things for 1.20.4 plugin version, let me know if this helps you.

https://spark.lucko.me/akqiLep2On

Here we are with more players, sadly it isn't doing so well

**Comment by GC-spigot** [comment]
While we're looking into what optimization we can do, we can suggest lowering the view distance - this should reduce some lag for you. We have had positive feedback on performance from other servers, and are looking into what is causing this case. Thanks!

**Comment by GC-spigot** [comment]
Should be improved!
