### ISSUE TITLE
Add blacklist of light blocks that make temperature raise 

### ISSUE THREAD

**Issue by homerek111** [AdvancedPlugins/Seasons#44]
### Describe the feature

It would be a really useful feature to allow adding some light blocks like LIGHT / GLOWSTONE / LANTERN to the blacklist so it won’t make the temperature go up when you are next to it

**Comment by GC-spigot** [comment]
Hey, we'll work on this. Currently we simply take the ambient light around the player, not dependent on the block. Thanks for the suggestion.
