### ISSUE TITLE
make actionbar more flexible

### ISSUE THREAD

**Issue by homerek111** [AdvancedPlugins/Seasons#45]
### Describe the bug

Actionbar temperature system should be more flexible to work with other plugins... 
Some plugins sometimes notify something using actionbar - it pops out for just a moment and gets overrided by the temperature again... 

It would be cool to be able to configurate temperature actionbar for some lower priority to allow other plugins use actionbar as well

### How to reproduce

use plugin

### Screenshots / Videos

![1775](https://github.com/AdvancedPlugins/Seasons/assets/93496464/620e9def-cddb-4a67-b087-359a715346ca)

**Comment by Mitality** [comment]
Great idea

**Comment by GC-spigot** [comment]
Added!
