### ISSUE TITLE
Blizzard Errors in Console

### ISSUE THREAD

**Issue by dtawales** [AdvancedPlugins/Seasons#47]
### Describe the bug

Unknown errors generating every few seconds during snowfall in Winter. Unknown what it does or what it is supposed to do.

### How to reproduce

Unknown. New plugin owner, have been seeing this since first install.

### Screenshots / Videos

![Screenshot 2024-02-21 164646](https://github.com/AdvancedPlugins/Seasons/assets/76761722/7033013c-93a4-4a0a-8322-0e25acc30596)

**Comment by GC-spigot** [comment]
Hey, thanks for the report. Fixed!
