### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by Oceanidas** [AdvancedPlugins/Seasons#49]
### Describe the bug

I'm having a memory issue. I asked for support and they tried to provide solutions, but unfortunately, we couldn't solve it. When I install the plugin on my server, it consumes memory absurdly, going from 4GB to 10/20GB in just 1 hour or less, which is not normal. Sometimes it's at 7GB and goes up to 20GB non-stop in a matter of minutes, for no apparent reason... I've already sent all kinds of spark/timings and it seems they don't show anything. I did some tests in which I explore and load chunks in the world, but even when I'm standing in the world, doing nothing, it continues to consume memory for no reason, making it impossible for me to use the plugin. My server are survival 1.19.4. I tried to put the plugin on my other server (creative 1.20.1) and the issue continues...

> Tests I've already conducted:
With the configuration reset
With my own configuration
With world chunk pre-loading and without pre-loading
With Aikars flag and without Aikars flag

OBS: My server isnt lagging (TPS 20)
On support they assisted me in posting it on GitHub

### How to reproduce

I tried to reproduce it by exploring the world and loading chunks, but later I noticed that even when doing nothing on my land, it kept loading memory endlessly.

### Screenshots / Videos

Some spark/timings (with aikars flag):
https://spark.lucko.me/Koa3tgTgGi

Prints:
https://imgur.com/a/VkPVAvr

**Comment by GC-spigot** [comment]
Hey, we'll do an update - please let us know if it helps you.
