### ISSUE TITLE
Add customization for temperature based events

### ISSUE THREAD

**Issue by purejosh** [AdvancedPlugins/Seasons#5]
### Describe the feature

It would be cool if there was a config we could edit, for the effects that a player undergoes when at certain temperatures. Even if the ones that are default in the plugin are hard coded, maybe we could create a value like `custom_temp_event_1` which lets us add status effects and player attribute modifiers using a separate config file.

For example, I would love to add an exhaustion/dehydration effect to the player if it's too hot, instead of making them catch fire. That would be incredible.

**Comment by GC-spigot** [comment]
Added for next update!
