### ISSUE TITLE
callender shows wrong season (not synchronised)

### ISSUE THREAD

**Issue by homerek111** [AdvancedPlugins/Seasons#51]
### Describe the bug

As I described everything on ticket via discord - I updated the plugin into the newest version and the day after that my players reported me that callender says different season than it actually is (to correct season was showed on actionbar)

I tried to synchronise it manually using command "/season setseason X" - and it seems to be synchronised now... BUT i think it shouldnt be the way to do it...

If you need my config files, etc - everything is share in my discord ticket #aseasons-0085

### How to reproduce

use 1.1.4 version of advancedseasons

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Seasons/assets/93496464/398290f6-6abb-49e6-b394-9f232f8f27e0)
![image](https://github.com/AdvancedPlugins/Seasons/assets/93496464/9e419fb7-3fc7-424b-ab85-9a342ba5db7e)

**Comment by homerek111** [comment]
My callendar got desynchronised again... so using /seasons setseason command fixes it only temporarly... 
There must be something that breaks it

**Comment by homerek111** [comment]
please take a look at that issue - it totally breaks usage of callendar...

**Comment by GC-spigot** [comment]
Hey I'm looking into it!

**Comment by homerek111** [comment]
> Hey I'm looking into it!

Any results??? It happened on my server again

**Comment by homerek111** [comment]
@GC-spigot any chance of taking a look at this bug?

**Comment by homerek111** [comment]
Any chance for taking care of this issue soon? @GC-spigot

**Comment by homerek111** [comment]
@GC-spigot by "completed" you mean abandoned or you actually gonna implement it in upcoming updates?
