### ISSUE TITLE
Temperature check dosnt work

### ISSUE THREAD

**Issue by KaspaMaspa09** [AdvancedPlugins/Seasons#54]
### Describe the bug

Hello, I have a problem with the temperature on the server. I found multiple spots on the map where the temperatureFormula donst apply even if Im on the same biome (1 block away from another). 

I use the terralith biomeConfig and I have the standard configuration for the temperature.yml

 On the screenshots below you can see the temperature difference and the biome.

### How to reproduce

Use terralith biomeConfiguration
Use terralith datapack

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Seasons/assets/133053067/226c8097-ff89-43e9-b8e2-487d4f2d006b)
![image](https://github.com/AdvancedPlugins/Seasons/assets/133053067/abd3849b-739f-4a6d-a382-ff1a7dd49777)

**Comment by GC-spigot** [comment]
Hmm, could it be there’s some light? It would be great if you recorded a video to recreate the issue for us.

**Comment by KaspaMaspa09** [comment]
You can see the light level on the screenshots above 
I will try to record something 
![image](https://github.com/AdvancedPlugins/Seasons/assets/133053067/c86c1309-a86a-4380-addd-ff85825920b7)

**Comment by KaspaMaspa09** [comment]
Here is the video
https://streamable.com/zhjuiz

**Comment by GC-spigot** [comment]
Hey, the video says "This video isn't available anymore". Can you upload an unlisted video to youtube? thanks!

**Comment by KaspaMaspa09** [comment]
https://www.youtube.com/watch?v=MRSDX7noxLs

**Comment by GC-spigot** [comment]
In that video unfortunately those are different biomes, that's why water isn't freezing there either. It's like walking from a desert to a forest biome, it's not much I can do.
