### ISSUE TITLE
An Option to hide the biomes somehow for lunar client

### ISSUE THREAD

**Issue by xanthacreator** [AdvancedPlugins/Seasons#55]
### Describe the feature

This seems to be an issue in lunar client where I guess it doesnt handle the biome correctly some areas it works fine others it doesnt
![image](https://github.com/AdvancedPlugins/Seasons/assets/84642413/b3edc8db-c707-4c11-bdb6-bba99143c5d5)
![image](https://github.com/AdvancedPlugins/Seasons/assets/84642413/819f74f3-2d67-408c-9cfb-900f5857be12)

Ive found this happens with other seasons too
![image](https://github.com/AdvancedPlugins/Seasons/assets/84642413/5552ba59-e50b-42fe-b368-29b1197e81e9)
![image](https://github.com/AdvancedPlugins/Seasons/assets/84642413/d0e634c9-c8fd-48ca-8b43-4d7eaf2be8de)

**Comment by xanthacreator** [comment]
It makes it difficult for servers to hide what plugins they use basically

**Comment by GC-spigot** [comment]
Cannot do unfortunately, those are the names plugin uses :/
