### ISSUE TITLE
Random Crashing Event

### ISSUE THREAD

**Issue by kill3rbytezzz** [AdvancedPlugins/Seasons#63]
### Describe the bug

Running the plugin on 1.1.8 version.
World already rendered using chunky, very few amount of player online and then suddenly the server crashed, the error message mostly mentions AdvancedSeason and I've tried to open ticket and discord and they direct me here, to Github issue
Server Specification
- R5 5600x
- 32 GB DDR4 RAM
- NVME Storage
- Linux based OS
Using latest version of PurpurMC 1.20.4

### How to reproduce

I have no idea how to reproduce this, the server suddenly crashed at random time, but there is one thing that certain, running command `/seasons setseason "season" world` when tehere is player on the server would crash the server.

### Server Log

https://mcpaste.io/8ffc809d9d758086

**Comment by GC-spigot** [comment]
Hi! Thanks for reporting this, have you done any modifications to the default configuration?

**Comment by GC-spigot** [comment]
I reworked a little part which may have caused a crash for you, it will be stable now :)
