### ISSUE TITLE
Holding items like torch/ice could rise/dicrease the temperature 

### ISSUE THREAD

**Issue by homerek111** [AdvancedPlugins/Seasons#65]
### Describe the feature

As title says - add an option to specify what items/blocks should rise/decrease the temperature while holding them in hand

**Comment by homerek111** [comment]
Any chance for adding this feature soon? @GC-spigot

**Comment by dstmart** [comment]
bro, we really need this feature

**Comment by homerek111** [comment]
@GC-spigot this feature would take plugin to another level - would be nice to conside adding it :)

**Comment by homerek111** [comment]
@GC-spigot by "completed" you mean abandoned or you actually gonna implement it in upcoming updates?
