### ISSUE TITLE
Task #182 spamming in console

### ISSUE THREAD

**Issue by thewickening** [AdvancedPlugins/Seasons#66]
### Describe the bug

Getting this spammed quite frequently in console.
[16:38:57 WARN]: [AdvancedSeasons] Task #182 for AdvancedSeasons v1.2.0 generated an exception
java.lang.NullPointerException: null
Like 11-12 times per second
I am using latest paper spigot 1.20.4

### How to reproduce

I have no idea.

**Comment by GC-spigot** [comment]
Without a server log this is impossible to figure out for ya :) attach it!

**Comment by thewickening** [comment]
> Without a server log this is impossible to figure out for ya :) attach it!

Apologies, https://mclo.gs/NbLaHoe

**Comment by thewickening** [comment]
> Without a server log this is impossible to figure out for ya :) attach it!

I am also getting a new one now, which is #208 related to griefdefender it seems.
https://mclo.gs/mCSaVKF

**Comment by GC-spigot** [comment]
Fixed for next update :)
