### ISSUE TITLE
Visual Bug Seeing Snow and Rain During summer

### ISSUE THREAD

**Issue by xanthacreator** [AdvancedPlugins/Seasons#68]
### Describe the bug

I'm seeing Snow and Rain in the middle of the summer season and i dont know why
![image](https://github.com/AdvancedPlugins/Seasons/assets/84642413/276e9b94-1034-458a-b0da-f9e9d61e7c58)

### How to reproduce

I'm not actually sure why or how it happened I was told to forward this issue 

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Seasons/assets/84642413/3ff2c03f-c45b-48e1-8eb1-b71f513d1a64)

### Server Log

https://mcpaste.io/789a3ddc011acf83

**Comment by xanthacreator** [comment]
![image](https://github.com/AdvancedPlugins/Seasons/assets/84642413/da34ad43-de0b-4419-8f2f-617c77a9f1d9)
![image](https://github.com/AdvancedPlugins/Seasons/assets/84642413/d61f554a-1afc-404c-96e9-0d2340cfc557)
 
 And its the same biome so its not a world generation thing

**Comment by HokoriStan** [comment]
I'm also having issues with seasons change. Is there a region set with worldguard maybe? For me, it seems to save the season's status when I define one. It goes away when I delete the region.

**Comment by xanthacreator** [comment]
No I have not set any Worldguard flags/regions

**Comment by HokoriStan** [comment]
Hm... ok. What about a biome that has been changed? That is also one of the issues for me.
Curious what might've happened before this happened. The sooner we can both provide the devs with good info, the sooner it's fixed 👍 

I want to recreate some scenario's that might've triggered this for you to happen, so we can double check if it's only your server, or it's the plugin itself.

**Comment by xanthacreator** [comment]
After some playing around I Found setting the season to winter seems to make everything snow again however when a transition to spring occurs it also appears to last through summer and fall. its almost like not everything is transitioning for the weather? But If you mean by changing the biomes with worldedit then no. I've done nothing to alter biomes in anyway this for some reason just happened. Also I've noticed this bug does not occur on AdvancedSeasons 1.1.3 only 1.1.9 and up for me. I haven't tested anything else besides 1.1.3 thats below 1.1.9 because I don't have access to it.

**Comment by xanthacreator** [comment]
https://youtu.be/Sv2_AJYfR94
Heres a video of me setting the season to winter first then transitioning to give you the visual idea of what im talking about.

**Comment by GC-spigot** [comment]
Hi! I'll look into this ASAP and have it figured out. Are you guys playing on bedrock when this is happening?

**Comment by xanthacreator** [comment]
no this is on java

**Comment by xanthacreator** [comment]
any update on this?

**Comment by GC-spigot** [comment]
So I looked into this, this is happening because biomes are updated slowly around the player, and it's still thinking the biome is winter. The gradual change causes this and we can't actually really do much. It takes up to a minute for biomes to update around the player and it's better visible with proper terrain, as seen here in the gif: https://gyazo.com/c792d631e592b6a892c9a07d4c4b6b86

Only possible change is to speed up biome transitions in config but that will cause more stress to the server and in the end may cause lag.

**Comment by xanthacreator** [comment]
i dont understand this didnt happen on advancedseasons 1.1.3
