### ISSUE TITLE
Advanced Season generates a lot of lag!!!

### ISSUE THREAD

**Issue by GJ-Euphory** [AdvancedPlugins/Seasons#69]
### Describe the bug

Advanced Season generates a lot of lag!!!

Here I leave you a Spark link so you can see how this plugin consumes a lot on my server!
https://spark.lucko.me/SaEBzTidO3

### How to reproduce

I don't understand much but I suppose the change of biomes has a lot to do with it!

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Seasons/assets/122542736/a7d760b8-35a3-4231-8087-3ee08813698c)

**Comment by GC-spigot** [comment]
Hi! Go into config.yml change chunkUpdates value to something lower like 3 for yourself. Reduce chunkRadius to 5. This will help by a lot. Ill reduce the default numbers as well.

**Comment by GJ-Euphory** [comment]
The thing is that at first, no matter how many players there are, everything goes well, but after a while the server slows down to the point of being unplayable.
