### ISSUE TITLE
Raining in Winter

### ISSUE THREAD

**Issue by EmanuelNorsk** [AdvancedPlugins/Seasons#7]
### Describe the bug

It rains when the temperature is way below 0 Celsius. This looks very weird.
Edit: This happens in winter transition 1 to 3 even if the temperature is way colder than 0C.

Edit2: In fall transition 3, it snows in some chunks and rains in some chunks even though the temperature is way below 0C. I have set custom temperatures for each season so it is lower than what it is by default. This should not change the problem with temperatures and when it is supposed to rain vs snow.

### How to reproduce

Change the season to winter. Either wait for it to rain, or summon rain.

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Seasons/assets/58894136/e5678637-a442-4e89-a8e1-fa35ac96c0cd)

**Comment by GC-spigot** [comment]
Fixed!
