### ISSUE TITLE
Snowfall not working correctly.

### ISSUE THREAD

**Issue by HokoriStan** [AdvancedPlugins/Seasons#70]
### Describe the bug

Upon season change from Autumn to Winter (and having no region defined with WorldGuard), most of the areas will get covered with snow, but for some reason, the snow skips certain locations as seen in the screenshot. 

The plugin is basically useless right now for my server. It doesn't generate the thing it is advertised to do.

### How to reproduce

One of the issues is WorldGuard and/or //setbiome command. Either one defines a region which is saved and cannot be overwritten by AdvancedSeasons. Even tho AdvancedSeasons is hooked into WorldGuard. (See server log)

### Screenshots / Videos

![2024-04-03_12 52 33](https://github.com/AdvancedPlugins/Seasons/assets/12199815/41708f1b-2edc-4fa2-b7b3-d589c347eb37)
![2024-04-03_12 52 43](https://github.com/AdvancedPlugins/Seasons/assets/12199815/5859a972-b14e-4ead-bc98-2f47525e1ec9)
![2024-04-03_12 52 51](https://github.com/AdvancedPlugins/Seasons/assets/12199815/bde60de8-c120-4b9d-91d3-67a8507c3046)

### Server Log

https://mcpaste.io/2e9da6e09d5197f8

**Comment by HokoriStan** [comment]
Edit: upon reinstalling the plugin, SOME of the squares that previously blocked snow, now generate snow. But there are still a lot of areas that does not generate snow. Spots that now generate snow don't have a region defined.

**Comment by GC-spigot** [comment]
Resolved in plugin as well now
