### ISSUE TITLE
Player selectable temperature scale

### ISSUE THREAD

**Issue by Paul-DK** [AdvancedPlugins/Seasons#79]
### Describe the feature

What it says in the title, really. I have players in the EU and NA and neither are comfortable with the others’ temperature scale (°F/°C). Allowing this functionality and providing the scale name, °F or °C, in a placeholder, like %advancedseasons_tempscale%, would be brilliant. Thanks :)

**Comment by GC-spigot** [comment]
Great idea! We'll add a command players can use to switch between c and f!

**Comment by GC-spigot** [comment]
Added for next update
