### ISSUE TITLE
The time of the world does not pass properly.

### ISSUE THREAD

**Issue by Ferippu** [AdvancedPlugins/Seasons#80]
### Describe the bug

The time is set to last 120 minutes, however the time is lasting like in Vanilla (10/10 minutes). Time is also frozen and to fix this I had to make a Skript to run "/gamerule dodaylightcycle True", however time passes like Vanilla. (I opened it again, as my problem was not solved and I did not see that they had answered the previous one. Sorry :/ )

### How to reproduce

I've tried all kinds of "time", if it goes over 20 minutes it doesn't work as it should. I didn't see any errors in the server console.

### Screenshots / Videos

![image](https://github.com/AdvancedPlugins/Seasons/assets/157979455/0c4bee38-17fc-4d88-98a9-f22ac46abaa6)

**Comment by GC-spigot** [comment]
Our system allows right now max day length of total 20 minutes, so e.g. day can be 19 minutes and night 1 is the max/min. Gamerule must be disabled for the time to be handled custom as well.

**Comment by Ferippu** [comment]
But the maximum time I can set is 20 minutes for the whole day?
