### ISSUE TITLE
New placeholder displaying incorrect information

### ISSUE THREAD

**Issue by Paul-DK** [AdvancedPlugins/Seasons#81]
### Describe the bug

The recent placeholder addition: %advancedseasons_temperature_icon%, as described in the recent changelog, returns the temperature in numbers, and not the weather icon.

### How to reproduce

Include the placeholder in a Scoreboard or something

**Comment by GC-spigot** [comment]
Found the problem! Was a priority problem wtih PAPI overriding `temperature_icon` placeholder with `temperature` one. Fixed next version in a few hours :)
