### ISSUE TITLE
Grass blocks are discolored, out of season

### ISSUE THREAD

**Issue by purejosh** [AdvancedPlugins/Seasons#82]
### Describe the bug

The season on my server is spring/summer, and there are blocks that appear to be stuck in winter mode. See screenshot below. This started happening while I was using AS v1.1.2, and I've updated to v1.2.2 with no change. Breaking the block and placing it again fixes the discoloration. 

Is there a way to repair my world? 

### How to reproduce

Unsure how to reproduce. 

### Screenshots / Videos

![2024-04-13_18 36 13](https://github.com/AdvancedPlugins/Seasons/assets/70633949/ab98a03c-169e-4471-955b-03d19da32f51)

**Comment by purejosh** [comment]
No, relogging doesn't help. I can transfer the world to a single player, and it'll be present there too, with no plugins. The only thing that fixes it is breaking and placing the block again.

**Comment by GC-spigot** [comment]
That is extremely weird, it's all done with protocollib and packets, no biomes are changed anywhere in data or world. I'll test it out more.
