### ISSUE TITLE
No rain or snow

### ISSUE THREAD

**Issue by Pilvinen** [AdvancedPlugins/Seasons#91]
### Describe the bug

Spigot with Minecraft 1.20.6
Latest AdvancedSeasons downloaded today.
ProtocolLib dev [#689] May 6, 2024, 5:02 PM

Using /weather rain doesn't result in rain or snow. I tried disabling all other plugins except AdvancedSeasons and ProtocolLib, but when AdvancedSeasons is installed it just doesn't work anymore.

No errors on console. Nothing in logs.

### How to reproduce

1) Install Spigot 1.20.6.
2) Install AdvancedSeasons.
3) Set season to winter.
4) /weather rain

### Screenshots / Videos

https://streamable.com/pdot58

**Comment by Pilvinen** [comment]
Tested. Still present in AdvancedSeasons 1.2.7 update.

**Comment by Pilvinen** [comment]
Oh,  this is interesting.
1) I deleted the jar.
2) Restarted.
3) Set /weather rain
4) Stopped the server.
5) Copied the AdvancedSeasons jar back.
6) Started the server.
7) Added the world + set season to winter:

![kuva](https://github.com/AdvancedPlugins/Seasons/assets/4374351/db0a343e-3926-428a-9c08-d06a3822532f)

**Comment by Ynverxe** [comment]
By the moment, AS handles raining by their own during winter. If you want to change the weather using commands, you try using PaperMC, but every 20 seconds the raining can return. Actually AS ignores `/weather` command on Spigot.

**Comment by Pilvinen** [comment]
> By the moment, AS handles raining by their own during winter. If you want to change the weather using commands, you can try using PaperMC, but every 20 seconds the raining can return. Actually AS ignores `/weather` command on Spigot.

Be as it may, but the real issue is that it never rains naturally.

**Comment by Ynverxe** [comment]
Tested it, this bug actually happens on Spigot, using PaperMC should not have any problem.

**Comment by Pilvinen** [comment]
> Tested it, this bug actually happens on Spigot, using PaperMC should not have any problem.

That's great. Unfortunately I'm using Spigot.

I also tested on Spigot 1.20.4 and the issue seems to be present there also. It doesn't seem any more stable than 1.20.6.

**Comment by Ynverxe** [comment]
Fixed. Wait for the next update.

**Comment by Pilvinen** [comment]
Seems to be fixed, but now it's always raining/snowing.

Should I open a new ticket for that... ?

**Comment by Pilvinen** [comment]
As a workaround, disabling custom weather in weather.yml seems to do the trick.
