### ISSUE TITLE
Water doesn't freeze in winter

### ISSUE THREAD

**Issue by Pilvinen** [AdvancedPlugins/Seasons#92]
### Describe the bug

Spigot with Minecraft 1.20.6
AdvancedSeasons 1.2.7 update.
ProtocolLib dev [#689] May 6, 2024, 5:02 PM

Water doesn't freeze during winter.
I tried disabling all other plugins except AdvancedSeasons and ProtocolLib.

No errors on console. Nothing in logs.

### How to reproduce

1) Install Spigot 1.20.6 and dev version of protocolLib that runs on 1.20.6
2) Install AdvancedSeasons.
3) Set season to winter.
4) Nothing happens to water.

### Screenshots / Videos

https://snipboard.io/8rXLsh.jpg

**Comment by Ynverxe** [comment]
Try using the default config. If the problem dissapears, send all your config files to see where's the error.

**Comment by Ynverxe** [comment]
Another thing, go to the river/ocean and then use F3 to determine the biome name, then go to biomeConfiguration/<the biome name that appears in F3>.yml and check that the `winter.winter-frezee` section is in TRUE. If not, set it to "true", restart your server and run /season setseason <any season> and /season setseason winter and check.

**Comment by Pilvinen** [comment]
Biome settings are on defaults.

I also set the calendar.yml to default settings and restarted in between. It seemed to make no difference, the issue still persists.

But I will try to isolate it further by setting up a Spigot 1.20.6 test server which runs only ProtocolLib and AdvancedSeasons on default settings. I will report back how it goes later today.

**Comment by Pilvinen** [comment]
![kuva](https://github.com/AdvancedPlugins/Seasons/assets/4374351/27a8cab3-7b08-4241-9bd0-50323ff7faea)

Not sure if the chunk info is relevant or what it means exactly. But it's showing spring.

**Comment by Pilvinen** [comment]
Seems like water doesn't freeze in winter unless it's raining (?) so this is likely the  same issue as ticket #91
