### ISSUE TITLE
Crop growth multiplier doesn't affect growth of pitcherplant

### ISSUE THREAD

**Issue by Pilvinen** [AdvancedPlugins/Seasons#94]
### Describe the bug

Spigot with Minecraft 1.20.6
Latest AdvancedSeasons.
ProtocolLib dev [#689] May 6, 2024, 5:02 PM

Crop growth multiplier doesn't affect growth of pitcherplant.

### How to reproduce

Install Spigot 1.20.6 and dev version of protocolLib that runs on 1.20.6
Install AdvancedSeasons.
Set growth to low value.
Plant a pitcher plant.
Watch it grow like crazy.

**Comment by Ynverxe** [comment]
Normally this plant should be 2 blocks, by chance the plant doesn't grow from 1 block up and looks like a cropped texture?

**Comment by Pilvinen** [comment]
> Normally this plant should have 2 blocks, by any chance the plant doesn't grow from 1 block up and looks like a clipped texture? I tried it and that's what's happening to me, I want to make sure it's the same behavior as yours.

For me it looks visually normal, it just grows very very fast.

**Comment by Ynverxe** [comment]
> For me it looks visually normal, it just grows very very fast.
Can I see your crops.yml?

**Comment by Pilvinen** [comment]
> > For me it looks visually normal, it just grows very very fast.
> > Can I see your crops.yml?

# Is custom crops handling enabled?
enabled: true

# Crop growth multiplier
growth:
SPRING: 0.8
SUMMER: 1.0
FALL: 0.5
WINTER: 0.25

winterGrowth:
# Should crops only grow in winter if they are lit up and in positive temperature, as well as under a block?
# If set to false, crops will bypass the checks and use value set from growth setting for winter.
# If set to true, if crop doesn't pass the checks it will not grow.
basedOnConditions: true
# Temperature needed for crops to grow in winter
tempThreshold: 10

**Comment by Ynverxe** [comment]
Hi, after do a little research, this bug is caused because Spigot doesn't takes care the grow of certain plants. So when a PitcherCrop is growing the server never calls the API. This bug is fixed on PaperMC.

https://github.com/PaperMC/Paper/pull/9242
https://github.com/PaperMC/Paper/blob/master/patches/server/0842-Call-BlockGrowEvent-for-missing-blocks.patch
