### ISSUE TITLE
calendar.yml has no effect on day length

### ISSUE THREAD

**Issue by Pilvinen** [AdvancedPlugins/Seasons#95]
### Describe the bug

Spigot with Minecraft 1.20.6
Latest AdvancedSeasons.
ProtocolLib dev [#689] May 6, 2024, 5:02 PM

Using calendar.yml to adjust time length has no effect whatsoever.

### How to reproduce

    Install Spigot 1.20.6 and dev version of protocolLib that runs on 1.20.6
    Install AdvancedSeasons.

```
time:
# In Vanilla: entire day in normal minecraft is 20 minutes
spring:
# Length of day time, in real world minutes
dayLength: 40
nightLength: 40
summer:
dayLength: 60
nightLength: 20
fall:
dayLength: 40
nightLength: 40
winter:
dayLength: 28
nightLength: 52

# Seasons Progression
progression:
# Should season progression be paused? Set to true to pause
paused: false

calendar:
# How many days should one season last
seasonDays: 2
# How many days should it take to transition between seasons?
transitionDays: 1
```

This config results in 100% normal 20 minute day length.

**Comment by Ynverxe** [comment]
This is not a bug, it is common behavior. The custom time function is only for changing the length of the night or day without exceeding 20 minutes.
