### ISSUE TITLE
Aseasons ui doesn't work properly with Itemsadder [FIXED]

### ISSUE THREAD

**Issue by MProductionsmado** [AdvancedPlugins/Seasons#96]
### Describe the bug
When installing the ui for Itemsadder, it only shows the icons but doesn't show the background texture.
![2024-05-16_16 19 22](https://github.com/AdvancedPlugins/Seasons/assets/161770222/aff41ea9-e928-4ffd-acd5-d30a20f56dfe)

You can fix it by adding an UTF-8 character as symbol in the IA config like this:
![image](https://github.com/AdvancedPlugins/Seasons/assets/161770222/7856c51c-c9d0-41bb-9742-d66842fc1d6a)
After that replace the :seasons: and :seasons_shop: in the Aseasons menu config for the calendar and the seasons shop with the two utf symbols like this:
![image](https://github.com/AdvancedPlugins/Seasons/assets/161770222/05432047-4986-4946-a1a6-8cfa8e5feeb2)

Now do /iazip and /seasons reload

### How to reproduce

newest animated ui version with itemsadder

**Comment by Ricozaur** [comment]
Wasn't the solution for me, using latest UI with animations since May 24.
